apiVersion: v1
data:
  default.conf: |
    server {
            listen 80 default_server;
            #listen [::]:80 default_server ipv6only=on;

            listen 443 ssl;

            root /usr/share/nginx/html;
            index index.html;

            server_name localhost;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                    try_files  / =404;
            }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-10T00:10:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:default.conf: {}
    manager: kubectl-create
    operation: Update
    time: "2021-04-10T00:10:19Z"
  name: nginxconfigmap
  namespace: default
  resourceVersion: "2512834"
  uid: 8eff94e7-6efe-439c-9aee-339cff5d2647
